# Generated by Django 4.2.4 on 2023-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
