# Generated by Django 4.2.4 on 2023-09-06 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
